version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "33280:80"
    volumes:
      - files:/var/www/html
    networks:
      - internal
    depends_on:
      - php
      - sage
  php:
    image: php:fpm-alpine
    volumes:
      - files:/var/www/html
    networks:
      - internal
  sage:
    build:
      context: .
      dockerfile: sage/Dockerfile
    environment:
      - DEBUG=true
    volumes:
      - files:/files
    networks:
      - internal
volumes:
  files:
networks:
  internal:
    driver: bridge